package com.austin.financetracker.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a financial category for classifying transactions.
 * <p>
 * Categories help group transactions into meaningful buckets such as
 * "Food", "Rent", or "Salary". Each category has a unique name,
 * an optional description, and is associated with a {@link TransactionType}.
 * </p>
 */
@Entity
@Table(name = "categories")
public class Category {

    /**
     * The unique identifier for the category.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique name of the category.
     * <p>
     * Cannot be {@code null} and must be unique across all categories.
     * </p>
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * A short description of the category.
     * This field is optional.
     */
    private String description;

    /**
     * The type of transaction this category belongs to
     * (e.g., INCOME or EXPENSE).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    /**
     * Default constructor required by JPA.
     */
    public Category() {
    }

    /**
     * Constructs a new {@code Category} with the given name, description, and type.
     *
     * @param name        the name of the category (must be unique and not null)
     * @param description the description of the category (may be null)
     * @param type        the transaction type associated with the category
     */
    public Category(String name, String description, TransactionType type) {
        this.name = name;
        this.description = description;
        this.type = type;
    }

    /**
     * Returns the transaction type of this category.
     *
     * @return the {@link TransactionType} of this category
     */
    public TransactionType getType() {
        return type;
    }

    /**
     * Sets the transaction type for this category.
     *
     * @param type the {@link TransactionType} to assign
     */
    public void setType(TransactionType type) {
        this.type = type;
    }

    /**
     * Returns the unique identifier of this category.
     *
     * @return the ID of the category
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this category.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of this category.
     *
     * @return the name of the category
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this category.
     *
     * @param name the new name to assign
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of this category.
     *
     * @return the description of the category
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of this category.
     *
     * @param description the new description to assign
     */
    public void setDescription(String description) {
        this.description = description;
    }
}