package com.austin.financetracker.entity;

import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a financial transaction in the system.
 * <p>
 * A transaction records an amount, description, date, type, and its
 * associated {@link Category}. Transactions can be classified as
 * {@link TransactionType#INCOME} or {@link TransactionType#EXPENSE}.
 * </p>
 */
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * The unique identifier for this transaction.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The monetary amount of the transaction.
     * <p>
     * Cannot be {@code null}.
     * </p>
     */
    @Column(nullable = false)
    private BigDecimal amount;

    /**
     * A short description of the transaction.
     * <p>
     * Cannot be {@code null}.
     * </p>
     */
    @Column(nullable = false)
    private String description;

    /**
     * The date when the transaction occurred.
     * <p>
     * Cannot be {@code null}.
     * </p>
     */
    @Column(nullable = false)
    private LocalDate date;

    /**
     * The type of transaction.
     * <p>
     * Stored in the database as a string value ("INCOME" or "EXPENSE").
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    /**
     * The category associated with this transaction.
     * <p>
     * Many transactions can belong to a single category.
     * This relationship is {@link FetchType#LAZY} by default,
     * meaning the category is only loaded when explicitly accessed.
     * </p>
     * <p>
     * Cannot be {@code null}.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /**
     * Default constructor required by JPA.
     */
    public Transaction() {
    }

    /**
     * Constructs a new {@code Transaction} with the given details.
     *
     * @param amount      the monetary amount of the transaction
     * @param description a short description of the transaction
     * @param date        the date the transaction occurred
     * @param type        the type of the transaction (INCOME or EXPENSE)
     * @param category    the category this transaction belongs to
     */
    public Transaction(BigDecimal amount, String description, LocalDate date,
            TransactionType type, Category category) {
        this.amount = amount;
        this.description = description;
        this.date = date;
        this.type = type;
        this.category = category;
    }

    /**
     * Returns the unique identifier of this transaction.
     *
     * @return the transaction ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this transaction.
     *
     * @param id the ID to assign
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the monetary amount of this transaction.
     *
     * @return the amount
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the monetary amount of this transaction.
     *
     * @param amount the amount to assign
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Sets the description of this transaction.
     *
     * @param description the description to assign
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the description of this transaction.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the date when this transaction occurred.
     *
     * @return the transaction date
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Sets the date of this transaction.
     *
     * @param date the date to assign
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Returns the type of this transaction.
     *
     * @return the {@link TransactionType}
     */
    public TransactionType getType() {
        return type;
    }

    /**
     * Sets the type of this transaction.
     *
     * @param type the {@link TransactionType} to assign
     */
    public void setType(TransactionType type) {
        this.type = type;
    }

    /**
     * Returns the category associated with this transaction.
     *
     * @return the category
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the category for this transaction.
     *
     * @param category the category to assign
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Returns a string representation of this transaction.
     *
     * @return a string containing transaction details
     */
    @Override
    public String toString() {
        return "Transaction{" +
                "id=" + id + ", amount=" + amount +
                ", description='" + description + '\'' +
                ", date=" + date +
                ", type=" + type +
                ", category=" + category.getName() +
                '}';
    }

    /**
     * Compares this transaction to another object for equality.
     * <p>
     * Two transactions are considered equal if they have the same non-null ID.
     * </p>
     *
     * @param obj the object to compare
     * @return {@code true} if the objects are equal, {@code false} otherwise
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null || getClass() != obj.getClass())
            return false;
        Transaction that = (Transaction) obj;
        return id != null && id.equals(that.id);
    }

    /**
     * Returns the hash code for this transaction.
     * <p>
     * Based on the transaction ID. If the ID is {@code null}, returns 0.
     * </p>
     *
     * @return the hash code value
     */
    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
