version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
      - ./.secrets/firebase-service-account.json:/app/.secrets/firebase-service-account.json:ro
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/.secrets/firebase-service-account.json

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
