FROM node:20-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the rest of the app
COPY frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
